[package]
name = "felon-code"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "felon"
path = "src/felon.rs"

[[bin]]
name = "debug"
path = "src/debug.rs"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
rig-core = "0.20.0"
tokio = { version = "1.47.1", features = ["full"] }
